class AppIcons {
  static const String basePath = "assets/icons";
  static const String logo = "$basePath/Logoipsum.svg";
  static const String google = "$basePath/Google-icons.svg";
  static const String apple = "$basePath/Apple-icons.svg";
  static const String facebook = "$basePath/Facebook-icons.svg";
  static const String transporte = "$basePath/Transporter.svg";
  static const String traveler = "$basePath/Traveler.svg";
  static const String sendPackage = "$basePath/Send Package.svg";
  static const String carryPackage = "$basePath/Carry Package.svg";
  static const String clients = "$basePath/Clients.svg";
  static const String totalEarnings = "$basePath/Total Earnings.svg";
  static const String date = "$basePath/Date-icons.svg";
  static const String location = "$basePath/Location-icons.svg";
  static const String recent = "$basePath/Recent-icons.svg";
  static const String upcoming = "$basePath/Upcoming Trips.svg";
  static const String dashboardNavbar = "$basePath/Dashboard-navbar.svg";
  static const String messagesNavbar = "$basePath/Messages-navbar.svg";
  static const String myParcelsNavbar = "$basePath/My Parcels-navbar.svg";
  static const String publishTripsNavbar = "$basePath/Publish Trips-navbar.svg";
  static const String searchNavbar = "$basePath/sarch-navbar.svg";
  static const String partion = "$basePath/Partion-icons.svg";
  static const String save = "$basePath/Save-icons.svg";
  static const String camera = "$basePath/Camera=icons.svg";
  static const String verifa = "$basePath/verifa-icon.svg";
  static const String delivery = "$basePath/delveri-Icons.svg";
  static const String clothes = "$basePath/Clothes-icons.svg";
  static const String documents = "$basePath/Documents-icons.svg";
  static const String food = "$basePath/Food-Icons.svg";
  static const String medicines = "$basePath/Medicines-icons.svg";
  static const String inviteNew = "$basePath/Invite New-Icons.svg";
  static const String edit = "$basePath/Edit-icons.svg";
}
